// Birds Page
import 'package:animal/AnimalDetailPage.dart';
import 'package:flutter/material.dart';

class BirdsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AnimalDetailPage("Birds", [
      {"name": "Eagle", "image": "assets/eagle.jpg", "bio": "Eagles are large birds of prey known for their powerful flight and exceptional eyesight. They are found in various regions, including North America, Europe, Africa, and Asia. Eagles primarily feed on fish, small mammals, and other birds. They build their nests, called eyries, on high cliffs or tall trees. Eagles are known for their hunting skills and can spot prey from great distances. The bald eagle, a species native to North America, is the national bird of the United States. Eagles have a strong beak and sharp talons, which they use to catch and kill their prey. They are monogamous birds and often return to the same nesting site each year. Some eagles, like the golden eagle, are highly territorial. Eagles are symbols of strength, freedom, and power in many cultures."},
      {"name": "Parrot", "image": "assets/parrot.jpg", "bio": "arrots are colorful and intelligent birds found in tropical and subtropical regions worldwide. They are famous for their ability to mimic human speech and sounds. Parrots have strong, curved beaks and zygodactyl feet, meaning two toes point forward and two point backward, which helps them grasp branches and food. They primarily eat fruits, seeds, nuts, and nectar. Some of the most well-known species include macaws, cockatoos, and African grey parrots. Parrots are social birds and often live in flocks. Many parrot species are long-lived, with some reaching over 50 years in captivity. They use vocalizations and body language to communicate with each other. Due to habitat destruction and illegal pet trade, many parrot species are endangered. Parrots are known for their playful nature and strong bond with their owners in captivity."},
      {"name": "Sparrow", "image": "assets/sparrow.jpg", "bio": "Sparrows are small, agile birds found worldwide, often living close to human settlements. They are highly adaptable and thrive in urban, suburban, and rural environments. Sparrows primarily feed on seeds, grains, and small insects. These birds are social and often seen in flocks, especially during winter. Sparrows build their nests in tree holes, building crevices, and even roofs of houses. They have a short lifespan compared to larger birds, typically living 3–5 years in the wild. Male sparrows sing to attract females and defend their territory. House sparrows are one of the most common bird species, found in nearly every part of the world. Sparrows play an important role in controlling insect populations. Despite their small size, they are known for their energetic and cheerful behavior."},
      {"name": "Owl", "image": "assets/owl.jpg", "bio": "Owls are nocturnal birds of prey known for their exceptional hunting skills and ability to see in the dark. They have large, forward-facing eyes and a distinctive facial disk that helps direct sound to their ears. Owls are found on every continent except Antarctica. They primarily feed on rodents, insects, and small birds. Owls have silent flight, thanks to their specialized feathers that reduce noise. Some owl species, like the barn owl, are crucial for controlling rodent populations. They nest in tree hollows, caves, and abandoned buildings. Owls communicate through hoots, screeches, and whistles. In many cultures, owls are associated with wisdom and mystery. Some species, like the snowy owl, are adapted to cold environments and can survive harsh winters."},
      {"name": "Hawk", "image": "assets/hawk bird.jpg", "bio": "Hawks are birds of prey known for their sharp eyesight, powerful beaks, and strong talons. They are found in a variety of habitats, including forests, grasslands, and deserts. Hawks primarily hunt small mammals, birds, and reptiles. They have excellent vision, allowing them to spot prey from great distances. Some hawk species, like the red-tailed hawk, are common in North America. Hawks build their nests in tall trees or cliffs and are highly territorial. They use soaring and gliding techniques to conserve energy while searching for food. Hawks play an important role in maintaining the balance of ecosystems by controlling rodent populations. They are solitary hunters but may form pairs during the breeding season. Many hawk species migrate long distances to find suitable breeding or feeding grounds."},
      {"name": "Kingfisher", "image": "assets/kingfisher bird.jpg", "bio": "Kingfishers are brightly colored birds known for their ability to catch fish with remarkable precision. They are found near rivers, lakes, and coastal regions across the world. Kingfishers have sharp beaks and strong neck muscles that help them dive into the water to catch prey. Some species also eat insects and small amphibians. They build their nests in burrows along riverbanks. Kingfishers are known for their rapid wing beats and agile flight. They have excellent vision, even underwater, allowing them to locate prey with accuracy. The common kingfisher is one of the most widespread species, found in Europe, Asia, and Africa. Their feathers often appear iridescent due to light refraction. Kingfishers are symbols of peace and prosperity in many cultures."},
      {"name": "Flamingo", "image": "assets/flamingo bird.jpg", "bio": "Flamingos are large, wading birds famous for their striking pink feathers and long, slender legs. They are found in shallow lakes, lagoons, and coastal wetlands across Africa, the Americas, and Asia. Their pink color comes from carotenoid pigments in the algae and crustaceans they eat. Flamingos are highly social and live in large colonies. They use their specialized beaks to filter-feed on small aquatic organisms. During courtship, flamingos perform synchronized group dances. They build cone-shaped mud nests to protect their eggs. Flamingos can stand on one leg for long periods to conserve body heat. They are excellent swimmers despite spending most of their time wading. Flamingos are migratory birds and travel long distances to find suitable breeding and feeding grounds."},
      {"name": "Penguin", "image": "assets/penguin bird.jpg", "bio": "Penguins are flightless seabirds adapted to cold climates, mainly found in the Southern Hemisphere. The emperor penguin, the largest species, thrives in Antarctica. Penguins have waterproof feathers and a thick layer of fat to insulate against the cold. They are excellent swimmers, using their flippers to propel through the water at high speeds. Penguins primarily feed on fish, squid, and krill. They form large colonies for breeding, often enduring extreme weather conditions. Males incubate eggs while females hunt for food. Penguins communicate through vocalizations and body movements. Some species, like the Galápagos penguin, live in warmer regions. Penguins are highly social and often huddle together to conserve heat."},
      {"name": "Woodpecker", "image": "assets/woodpeacker bird.jpg", "bio": "Woodpeckers are birds known for their ability to peck at tree bark to find insects and create nesting cavities. They have strong beaks and specially adapted skulls that absorb shock. Woodpeckers are found in forests and woodlands worldwide. They primarily feed on insects, larvae, and tree sap. Some species also eat nuts and fruits. Woodpeckers have long tongues that help them extract food from deep crevices. Their feet have two toes facing forward and two facing backward, helping them grip tree trunks. Drumming on wood is a form of communication and territory marking. The downy woodpecker and pileated woodpecker are common species in North America. Woodpeckers play a crucial role in forest ecosystems by controlling insect populations."},
      {"name": "Macaw", "image": "assets/macaw bird.jpg", "bio": " Macaws are large, colorful parrots native to Central and South America. They are known for their intelligence, loud calls, and strong beaks. Macaws primarily eat fruits, seeds, and nuts, using their powerful beaks to crack open hard shells. Some macaws have been observed using tools in the wild. They form strong bonds with their mates and are highly social. Macaws have long lifespans, with some living over 50 years. Their vibrant feathers help them blend into tropical rainforests. Many macaw species are endangered due to habitat destruction and illegal pet trade. They are excellent flyers, covering large distances in search of food. Macaws play an essential role in seed dispersal, contributing to forest regeneration."},
      {"name": "Canary", "image": "assets/Canary BIRD.jpg", "bio": "Canaries are small songbirds known for their melodious singing ability. Originally from the Canary Islands, they are popular as pets worldwide. Male canaries sing to attract mates and establish territory. They are social birds but prefer to live in pairs or small groups. Canaries primarily eat seeds, fruits, and vegetables. Their bright yellow color is a result of selective breeding. In the past, miners used canaries to detect toxic gases in coal mines. Canaries thrive in captivity and are relatively easy to care for. They communicate using a variety of chirps and whistles. Canaries are active and enjoy flying, requiring spacious cages to stay healthy."},
    ]);
  }
}

// Fish Page
class FishPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AnimalDetailPage("Fish", [
      {"name": "Shark", "image": "assets/shark fish.jpg", "bio": "Sharks are large predatory fish known for their sharp teeth. They are found in oceans worldwide and are famous in regions like Australia and South Africa. Sharks are carnivores, primarily feeding on fish and marine mammals. They have excellent senses, detecting blood from miles away. Some species migrate long distances for breeding. Sharks are cold-blooded and prefer warm waters. They are apex predators, maintaining marine ecosystem balance. Some species can live for over 70 years.."},
      {"name": "Goldfish", "image": "assets/gold fish.jpg", "bio": "Goldfish are freshwater fish popular in aquariums. Originating from China, they are now found worldwide. They thrive in calm waters like ponds and tanks. Goldfish are omnivores, eating plants and small insects. They are social fish, often living in groups. Goldfish have excellent memory and can recognize their owners. They can change color based on diet and environment."},
      {"name": "Tuna", "image": "assets/tuna fish.jpg", "bio": "Tuna are fast-swimming fish found in tropical and temperate oceans. They are prized for their meat, making them popular in sushi. Tuna are carnivorous, feeding on smaller fish. They have streamlined bodies for efficient swimming. Some species, like the bluefin tuna, can reach speeds of 40 mph. Tuna migrate across oceans for feeding and breeding"},
      {"name": "Betta", "image": "assets/betta fish.jpg", "bio": "Betta fish are colorful freshwater fish native to Southeast Asia. They are known for their aggressive nature, especially among males. Bettas thrive in warm, still waters like rice paddies and ponds. They are carnivorous, feeding on insects and larvae. Betta fish can breathe atmospheric oxygen, allowing them to survive in low-oxygen environments."},
      {"name": "Catfish", "image": "assets/cat fish.jpg", "bio": "Catfish are bottom-dwelling fish found in freshwater rivers, lakes, and ponds worldwide. They are known for their whisker-like barbels, which help them sense food in murky waters. Catfish are highly adaptable and can survive in a variety of water conditions. They are omnivorous, feeding on small fish, insects, plants, and detritus. Many species are nocturnal, becoming more active at night. Some catfish, like the electric catfish, can produce electric shocks for defense. They are an important food source in many cultures and are farmed in aquaculture. Catfish play a vital role in aquatic ecosystems by helping clean up organic waste."},
      {"name": "Clownfish", "image": "assets/clown fish.jpg", "bio": "Clownfish are small, vibrant fish known for living among sea anemones. Found in the warm waters of the Pacific and Indian Oceans, they have a symbiotic relationship with anemones for protection. Clownfish are omnivores, feeding on algae and small crustaceans. They communicate through popping sounds and can change gender during their life cycle"},
      {"name": "Piranha", "image": "assets/piranha fish.jpg", "bio": "Piranhas are freshwater fish known for their sharp teeth and strong bite. They are found in South American rivers, especially in the Amazon Basin. Piranhas are carnivorous and feed on fish, insects, and small mammals. They are known for their feeding frenzies but generally scavenge. Some species also eat plant matter, making them omnivores. Piranhas play an important role in their ecosystem by keeping populations in balance."},
      {"name": "Guppy", "image": "assets/gold fish.jpg", "bio": "Guppies are small, colorful freshwater fish popular in aquariums. They originate from South America and thrive in warm, slow-moving waters. Guppies are omnivores, eating algae, insects, and small invertebrates. They are livebearers, meaning they give birth to live young instead of laying eggs. Guppies adapt well to different environments and are known for their rapid reproduction."},
      {"name": "Manta Ray", "image": "assets/manta ray fish.jpeg", "bio": "Manta rays are large, graceful fish found in tropical and subtropical waters. They are filter feeders, consuming plankton and small fish. Manta rays are known for their intelligence and social behavior. They have the largest brain of any fish. Unlike stingrays, they are harmless to humans. Manta rays migrate long distances and are crucial for marine biodiversity."},
      {"name": "Eel", "image": "assets/eel fish.jpg", "bio": "Eels are elongated, snake-like fish found in freshwater and saltwater habitats. Some species, like the electric eel, can generate electricity. Eels are nocturnal and hunt at night. They eat fish, invertebrates, and crustaceans. Many eels migrate to spawn, with some species traveling thousands of miles. Eels play a vital role in maintaining aquatic ecosystems."},
      {"name": "Angelfish", "image": "assets/angle fisj.jpg", "bio": "Angelfish are beautiful freshwater fish known for their distinctive shape. They originate from South America and are found in slow-moving rivers. Angelfish are omnivores, feeding on small invertebrates and plant matter. They are popular in aquariums due to their graceful movements and striking colors. Angelfish form strong pair bonds and are protective of their eggs."},
    ]);
  }
}

// Mammals Page
class MammalsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AnimalDetailPage("Mammals", [
      {"name": "Tiger", "image": "assets/tiger m.jpg", "bio": "Tigers are the largest wild cats, known for their distinctive orange fur with black stripes. They are apex predators and primarily hunt deer, wild boars, and other large mammals. Tigers are excellent swimmers, unlike most other big cats, and often cool off in water. They have powerful muscles and can leap up to 30 feet in a single bound. Tigers are solitary animals, marking large territories to avoid competition. Their roar can be heard up to 2 miles away, helping them communicate over long distances. Each tiger has a unique stripe pattern, much like a fingerprint. They are primarily nocturnal hunters, using their keen eyesight and stealth to ambush prey. Tigers play a vital role in maintaining the ecological balance of their habitats. Unfortunately, they are endangered due to habitat loss and poaching for their fur and body parts."},
      {"name": "Elephant", "image": "assets/elephant m.jpg", "bio": "Elephants are the largest land animals, known for their intelligence and strong family bonds. They use their long trunks for drinking, grabbing food, and even communicating through touch. Elephants are herbivores, consuming up to 300 pounds of vegetation daily. They have strong social structures, with matriarchs leading the herd. Elephants can recognize themselves in mirrors, demonstrating high cognitive abilities. Their large ears help regulate body temperature in hot climates. They communicate using low-frequency sounds called infrasound, which can travel long distances. Elephants have an incredible memory, remembering places, individuals, and migration routes for decades. They are capable of expressing emotions such as joy, grief, and compassion. Due to habitat destruction and poaching for ivory, elephants are classified as endangered."},
      {"name": "Lion", "image": "assets/lion m.jpg", "bio": "Lions are powerful big cats known as the 'kings of the jungle' due to their dominance in the animal kingdom. Unlike most cats, lions are social and live in groups called prides. A lion’s roar can be heard up to 5 miles away, serving as a warning or call to the pride. Male lions have a thick mane that protects them during fights and makes them appear larger. Female lions, or lionesses, are the primary hunters, working together to take down prey. Lions are opportunistic predators and can eat up to 15% of their body weight in one meal. Cubs are raised collectively by the females in the pride. Lions spend most of their day resting, sleeping up to 20 hours. They have excellent night vision, which helps them hunt in the dark. Lions play an essential role in the ecosystem by controlling prey populations."},
      {"name": "Leopard", "image": "assets/leopard m.jpg", "bio": "Leopards are stealthy and agile big cats known for their beautiful golden coats covered in black rosettes. They are excellent climbers and often drag their prey up into trees to avoid scavengers. Leopards are solitary animals, marking their territories with scent markings and scratches. They have powerful jaws and can take down prey much larger than themselves. Unlike lions, leopards rely on ambush tactics, using their incredible speed and stealth. They are capable of running at speeds up to 36 mph (58 km/h). Leopards can adapt to various habitats, from dense forests to deserts. They have excellent night vision, making them highly effective nocturnal hunters. Some leopards have melanistic genes, giving them an all-black appearance, known as black panthers. Despite their adaptability, leopards are threatened by habitat loss and poaching."},
      {"name": "Giraffe", "image": "assets/giraffe m.jpg", "bio": "Giraffes are the tallest land animals, native to the savannas of Africa. They can grow up to 18 feet tall, with their long necks helping them reach high tree branches for food. Their diet mainly consists of acacia leaves, which provide them with water and nutrients. Despite their long necks, they have the same number of neck vertebrae as humans—just larger in size. Giraffes are social animals, living in loose herds for protection. They have excellent eyesight, allowing them to spot predators from a distance. Male giraffes, called bulls, engage in “necking” battles to establish dominance. Giraffes only sleep for short periods, usually less than 30 minutes a day. Their tongues can be up to 18 inches long and are dark-colored to prevent sunburn. Although generally peaceful, they can deliver powerful kicks to defend themselves from lions and other predators"},
      {"name": "Zebra", "image": "assets/zebra m.jpg", "bio": "Zebras are horse-like mammals known for their striking black-and-white striped patterns. Each zebra has a unique stripe pattern, much like a human fingerprint. They are found in the grasslands and savannas of Africa, where they graze on grass and shrubs. Zebras are highly social and live in herds for protection against predators. They communicate through various vocalizations, body movements, and facial expressions. When threatened, zebras can run at speeds of up to 65 km/h (40 mph). Their stripes help in camouflage, confusing predators by making it difficult to single out an individual. Zebras are strong and can deliver powerful kicks to defend themselves. They have a close relationship with other herbivores like wildebeests, often migrating together in search of food and water. Unlike horses, zebras have never been successfully domesticated due to their unpredictable nature."},
      {"name": "Wolf", "image": "assets/wolf m.jpg", "bio": "Wolves are highly intelligent and social carnivores that live in packs led by an alpha pair. They are found in forests, tundras, and grasslands across North America, Europe, and Asia. Wolves communicate through howls, barks, and body language to coordinate hunts and maintain pack unity. They have strong teamwork and can take down large prey like deer, elk, and moose. Each wolf has a unique howl that helps identify individuals within the pack. Wolves play a crucial role in maintaining ecological balance by controlling prey populations. They are highly territorial and mark their range using scent glands and vocalizations. Wolf pups are born blind and rely on their pack for protection and learning survival skills. Despite their fearsome reputation, wolves are generally shy and avoid human contact. Wolves can travel long distances, covering up to 30 miles a day while hunting."},
      {"name": "Kangaroo", "image": "assets/kangaroom.jpeg", "bio": "Kangaroos are marsupials native to Australia, known for their powerful hind legs and jumping ability. They can leap up to 30 feet in a single bound and reach speeds of 40 mph. Female kangaroos carry their young, called joeys, in a pouch until they are strong enough to survive on their own. Kangaroos are herbivores, primarily feeding on grass, leaves, and shrubs. They have a unique reproductive system that allows them to pause embryo development during harsh conditions. Kangaroos use their tails for balance while hopping and can also use them as a tripod when standing still. They are social animals, often forming groups called mobs for protection. When threatened, they can deliver powerful kicks with their strong legs to defend themselves. Kangaroos are excellent swimmers and can use water as a means of escape from predators. They play a crucial role in maintaining the grassland ecosystem by preventing overgrowth."},
      {"name": "Panda", "image": "assets/panda m.jpg", "bio": "Giant pandas are native to China and are known for their black-and-white fur and gentle nature. They primarily eat bamboo, consuming up to 40 pounds of it daily. Despite being classified as carnivores, over 99% of their diet consists of plants. Pandas have an extended wrist bone that functions like a thumb, helping them grip bamboo. They are solitary animals and spend most of their time eating and resting. Pandas were once considered endangered, but conservation efforts have improved their population. They are excellent climbers and can also swim to escape predators. Baby pandas are born tiny, weighing only about 100 grams, and are completely dependent on their mothers. Pandas have a strong jaw and teeth adapted for crushing tough bamboo stalks. Due to their unique diet, they spend most of their day eating and digesting food."},
      {"name": "Chimpanzee", "image": "assets/Chimpanzee m.jpg", "bio": "Chimpanzees are highly intelligent primates closely related to humans, sharing about 98% of our DNA. They are native to African rainforests and are skilled at using tools to find food. Chimps are omnivores, eating fruits, nuts, insects, and occasionally meat. They live in large social groups and communicate through facial expressions, gestures, and vocalizations. Chimpanzees display emotions such as joy, grief, and empathy, much like humans. They use sticks to extract termites from mounds and leaves to collect water. Chimpanzees have a strong memory and problem-solving abilities. Young chimps learn survival skills by imitating older members of the group. They are excellent climbers and spend much of their time in trees. Sadly, chimpanzees are endangered due to habitat loss and poaching."},
      {"name": "Rhinoceros", "image": "assets/Rhinoceros m.jpg", "bio": "Rhinoceroses are large, thick-skinned herbivores known for their distinctive horns. They are found in Africa and Asia, with species like the white rhino, black rhino, and Indian rhino. Rhinos have poor eyesight but an excellent sense of smell and hearing. They are solitary animals and mark their territory using dung piles and scent glands. Despite their massive size, rhinos can run at speeds of up to 30 mph. They have a strong bond with oxpecker birds, which help them remove parasites. Rhino horns are made of keratin, the same material as human nails and hair. They play a crucial role in their ecosystems by shaping landscapes through their grazing habits. Rhinos enjoy mud baths, which protect their skin from the sun and insects. Due to poaching for their horns, many rhino species are critically endangered."},
      {"name": "Bison", "image": "assets/Bison m.jpg", "bio": "Bison are large, shaggy-haired herbivores found in North America and parts of Europe. They are the heaviest land mammals in North America, with males weighing over 2,000 pounds. Bison were once nearly extinct due to overhunting but have made a remarkable recovery through conservation efforts. They primarily graze on grasses and help maintain prairie ecosystems. Bison can run at speeds of up to 35 mph despite their large size. During mating season, males engage in head-butting contests to establish dominance. They have a thick coat that protects them from harsh winter conditions. Bison are social animals and live in herds for protection against predators. Native American cultures highly revere bison, using every part of the animal for food, clothing, and tools. Bison migration patterns have played a crucial role in shaping North American grasslands."},
    ]);
  }
}

// Reptiles Page
class ReptilesPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AnimalDetailPage("Reptiles", [
      {"name": "Cobra", "image": "assets/cobra r.jpg", "bio": "Cobras are venomous snakes known for their ability to raise the front part of their bodies and expand their hoods when threatened. They are found in Africa and Asia, thriving in forests, grasslands, and near human settlements. Their venom contains neurotoxins that can cause paralysis in their prey. Some species, like the king cobra, can grow up to 18 feet, making them the longest venomous snakes. Cobras primarily feed on rodents, birds, and other snakes. Some species, such as the spitting cobra, can spray venom to blind predators. Despite their dangerous reputation, cobras play a vital role in controlling rodent populations. They are featured in many cultural myths and are sometimes revered in Hinduism. Cobras rely on their forked tongues to detect chemical signals in the air. Habitat destruction and illegal wildlife trade threaten their populations." },
      {"name": "Crocodile", "image": "assets/crocodile r.jpg", "bio": "Crocodiles are large, semiaquatic reptiles known for their powerful jaws and armored bodies. They have existed for over 200 million years, surviving multiple mass extinctions. Found in tropical regions worldwide, they inhabit rivers, lakes, and coastal areas. Crocodiles are apex predators, feeding on fish, mammals, and birds. They use a unique 'death roll' technique to overpower prey. Their eyes and nostrils are positioned on top of their heads, allowing them to stay submerged while watching for prey. Crocodiles can go months without eating due to their slow metabolism. They have the strongest bite force of any animal, measuring over 3,700 psi. Some species, like the saltwater crocodile, can grow over 20 feet long. Despite their fearsome nature, they are crucial for maintaining wetland ecosystems."},
      {"name": "Gecko", "image": "assets/gecko r.jpg", "bio": "Geckos are small, nocturnal lizards known for their unique ability to climb smooth surfaces using their sticky feet. They are found in warm regions across the world, from deserts to rainforests. Geckos have specialized toe pads with microscopic hairs that allow them to cling to walls and ceilings. They communicate using chirping sounds, a rare trait among lizards. Some species can regenerate their tails if attacked by predators. Unlike most reptiles, geckos have excellent night vision and can see colors in the dark. Their skin is covered in tiny scales that repel water and bacteria, keeping them clean. Some species, like the leopard gecko, are popular pets due to their docile nature. Geckos play an essential role in controlling insect populations. They shed their skin periodically to maintain healthy growth."},
      {"name": "Komodo Dragon", "image": "assets/Komodo Dragon.jpeg", "bio": "Komodo dragons are the largest living lizards, reaching lengths of up to 10 feet and weighing over 150 pounds. They are native to a few Indonesian islands, including Komodo and Rinca. These apex predators have powerful limbs and a keen sense of smell, detecting prey from miles away. Komodo dragons have venomous saliva containing toxic proteins that weaken and immobilize their prey. They are opportunistic hunters, feeding on deer, birds, and even smaller dragons. Despite their size, they can run up to 12 mph when chasing prey. Young dragons spend their early years in trees to avoid being eaten by adults. They can consume up to 80% of their body weight in a single meal. Komodo dragons have a slow metabolism and can survive on a few large meals per year. Conservation efforts are in place to protect them from habitat destruction and poaching."},
      {"name": "Chameleon", "image": "assets/Chameleon r.jpg", "bio": "Chameleons are unique reptiles famous for their ability to change skin color, which helps with camouflage and communication. They are found mainly in Africa, Madagascar, and parts of Asia. Their specialized eyes can move independently, allowing them to look in two different directions at once. Chameleons use their long, sticky tongues to capture insects with lightning-fast speed. They rely on color changes to regulate body temperature, turning darker to absorb heat and lighter to reflect it. Some species have prehensile tails that help them grip branches while climbing. Chameleons are slow-moving but have an excellent sense of balance. Their zygodactylous feet, with two toes pointing forward and two backward, provide a strong grip. They are highly territorial and display bright colors during confrontations. Many chameleon species face threats from deforestation and the pet trade."},
      {"name": "Iguana", "image": "assets/Iguana r.jpg", "bio": "Iguanas are large, herbivorous lizards commonly found in Central and South America. They prefer warm, tropical environments, including rainforests and coastal regions. Iguanas have strong, clawed feet that help them climb trees and escape predators. They are excellent swimmers and can hold their breath for up to 30 minutes. Iguanas communicate using head bobs and body movements to establish dominance. They have a parietal eye on top of their heads, which helps detect predators from above. Their diets consist mainly of leaves, flowers, and fruits. Iguanas can detach their tails when threatened, allowing them to escape predators. They are cold-blooded and rely on sunlight to regulate body temperature. Some species, like the marine iguana, can dive underwater to feed on algae."},
      {"name": "Alligator", "image": "assets/Alligator r.jpg", "bio": "Alligators are large, semiaquatic reptiles found mainly in the southeastern United States and China. They have broader snouts compared to crocodiles and prefer freshwater habitats like swamps and rivers. Alligators are opportunistic predators, feeding on fish, birds, and small mammals. They have a powerful bite but prefer to avoid human encounters. During cold seasons, they enter a dormant state called brumation. Alligators use their tails to propel themselves through water with great speed. They have excellent night vision, making them effective nocturnal hunters. Females build nests from vegetation and fiercely protect their eggs. Unlike crocodiles, alligators have a more limited range and prefer warmer climates. They play an essential role in their ecosystem by creating 'gator holes' that provide water for other wildlife."},
      {"name": "Tortoise", "image": "assets/Tortoise r.jpeg", "bio": "Tortoises are slow-moving, land-dwelling reptiles known for their hard shells and long lifespans. They are found in dry regions, including deserts, grasslands, and forests. Tortoises are herbivores, primarily feeding on grasses, leaves, and fruits. Their shells are made of bone and provide protection from predators. Unlike turtles, tortoises cannot swim and prefer to stay on land. Some species, like the Galápagos tortoise, can live over 100 years. They have strong, elephant-like legs that help them traverse rough terrain. Tortoises are solitary creatures, only coming together for mating. They play a crucial role in seed dispersal by consuming and spreading plant material. Habitat destruction and illegal pet trade threaten many tortoise species."},
      {"name": "Python", "image": "assets/Python r.jpg", "bio": "Pythons are large, non-venomous snakes known for their ability to kill prey through constriction. They are found in Africa, Asia, and Australia, inhabiting forests, grasslands, and swamps. Pythons rely on heat-sensing pits near their mouths to detect warm-blooded prey in the dark. They ambush their prey and wrap their muscular bodies around them, suffocating them before swallowing them whole. Some python species, like the reticulated python, can grow over 20 feet long. Pythons have flexible jaws that allow them to consume prey much larger than their head. They can survive months without eating after consuming a large meal. Female pythons lay eggs and coil around them to provide warmth and protection. They play an essential role in controlling rodent populations. Due to habitat destruction and illegal trade, some python species face conservation concerns."},
      {"name": "Monitor Lizard", "image": "assets/Monitor Lizard r.jpg", "bio": "Monitor lizards are large, intelligent reptiles found in Africa, Asia, and Australia. They are excellent climbers and swimmers, adapting to a wide range of habitats. Monitor lizards are carnivorous, feeding on insects, small mammals, birds, and even carrion. Some species, like the Nile monitor, can grow over 7 feet long. They have sharp claws and strong tails, which they use for defense and balance. Monitor lizards have forked tongues, allowing them to detect scent particles like snakes. They are known for their problem-solving abilities and hunting strategies. Some species, like the Komodo dragon, have mild venom that weakens their prey. Their populations are threatened by habitat destruction and illegal pet trade."},
      {"name": "Gila Monster", "image": "assets/Gila Monster r.jpg", "bio": "Gila monsters are one of the few venomous lizards, native to the southwestern United States and Mexico. They have thick, beaded scales and a sluggish movement but can deliver a painful bite. Gila monsters store fat in their tails, allowing them to survive long periods without food. They primarily eat eggs, small mammals, and insects. Unlike snakes, they chew their venom into their prey rather than injecting it. Their venom has been studied for potential medical benefits, including diabetes treatment. They are solitary animals, only coming together for mating. Due to their slow metabolism, they do not need to eat frequently. Gila monsters are protected by law, as habitat loss threatens their survival."},
    ]);
  }
}
